### ISSUE TITLE
When will the experimental host-guest results be released for SAMPL9?

### ISSUE THREAD

**Issue by vvoelz** [samplchallenges/SAMPL9#6]
Asking for a friend.

**Comment by davidlmobley** [comment]
I've got them! Just need to format for upload, sorry for the delay. Part of the issue is that the logical person for me to ask is my student @amezcum1 who is still doing some reference calculations and it's probably better that he not see them til he finishes. (Feel free to e-mail with a link to your GitHub issue next time for faster response; sometimes I miss GitHub notifications.)

**Comment by davidlmobley** [comment]
Resolved - released.
